### PR TITLE
Add 'khaeru' to recipe-maintainers

### PR DESCRIPTION
**Pull request by khaeru**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by khaeru** [comment]
@conda-forge-admin, please rerender

**Comment by gidden** [comment]
@khaeru, I am on asking on the conda-forge gitter asking what to do about the appveyor failure. In the meantime, since we have a strict packaging dep on ixmp and are bumping the build number here, would you mind pring into ixmp-feedstock as well? Once that passes, we can repin the conda version.

**Comment by gidden** [comment]
Maybe its worth trying to bump the ixmp version and try again here?

**Comment by khaeru** [comment]
- At https://anaconda.org/conda-forge/ixmp/files, ixmp 0.1.3-2 is visible.
- At https://conda.anaconda.org/conda-forge/noarch/, only ixmp 0.1.3-1 is visible, not -2.
- I don't know why there is an Appveyor build on this PR when there wasn't one on the ixmp-feedstock one.

**Comment by gidden** [comment]
My guess is that we may have to remove appveyor manually, but was hoping to get some clarity from the conda-forge maintainers

**Comment by khaeru** [comment]
Removing the specific build version allowed the Azure Pipelines test to pass.

**Comment by gidden** [comment]
Another option is to ask the bot for a rerender again

**Comment by gidden** [comment]
Ok, the reason I added this was to guarantee that conda-forge is getting the right ixmp version, because if not, message_ix in the wild will yell (due to the weird java-message_ix dep). 

In that case, I would suggest adding a line (not now, but during the release build) that calls and executes the westeros example like:

```
python -c 'import message_ix; message_ix.testing.make_westeros(solve=True)'
```

This way, we test to be absolutely sure that everything is installed correctly.

**Comment by gidden** [comment]
In any case, I suggest that we wait for part of the day today for a gitter response. Barring that, we ask for one more rerender. If that fails, remove manually. Sound good or have another idea?

**Comment by scopatz** [comment]
This is OK to merge

**Comment by gidden** [comment]
Thanks @scopatz for the info! If we prefer to merge a "clean" pr, is that possible (with the above mentioned steps)? Or should we simply ignore the error and merge as is?

**Comment by gidden** [comment]
Ok! Per @scopatz's recommendation, merging as is.

**Pull request merged**
