### PR TITLE
MNT: remove noarch and re-render with conda-smithy 3.1.4, no changes made

### PR DESCRIPTION
**Pull request by gidden**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gidden** [comment]
Hi @jakirkham. While this PR appears to pass (`noarch` is removed), it did not trigger circleci (even though there exists a `.circleci/config.yml`). To note, #6 (which failed) also did not trigger circleci. When I try to access the project on circleci.com, I get `contact repo admins` as the only option (i.e., there is no "Follow" option). 

Everything from my end appears to be in order. Any ideas on why circle isn't hooking?

**Comment by jakirkham** [comment]
This normally ends up being a user settings' issue. So there's not a lot we can do from our end. Otherwise there are some suggestions that users that have had this problem provided to us.

> Otherwise (e.g. in a PR to staged-recipes), here are some things you can try:
> * Log in and out of Circle CI.
> * Revoke Circle CI’s access and then enable it again.
> * In the “Checkout SSH keys” section of your Circle CI project settings, press “add user key”.


ref: https://conda-forge.org/docs/ciservices.html#enabling-circle-on-your-fork

**Comment by gidden** [comment]
Thanks @jakirkham! I'll give it a shot in a bit.

**Comment by gidden** [comment]
Ok, looks like I had to reset circleci with conda admin (no one was following).

**Pull request merged**
