### PR TITLE
MNT: rerender

### LINKED ISSUE #3: @conda-forge-admin, please rerender
Should fix https://github.com/conda-forge/message-ix-feedstock/pull/2#issuecomment-390925787.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #3.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #3

### CODE REVIEW

**Comment by djsutherland** [comment]
Hmm. Why is it still trying to do an AppVeyor build?

Also seems like a false positive on `ff_ci_pr_build.py` for some reason.

Pretty confused. @conda-forge/core, I can't look into this more right now but stuff seems messed up with this repo somehow. Recipe looks fine to me though.

**Comment by gidden** [comment]
For now, I have addressed this issue by removing `noarch`, let me know if you'd like me to reopen.

**Comment by jakirkham** [comment]
It seems to still be in the `meta.yaml` though. 😕

**Comment by gidden** [comment]
Ai, yes, I thought it was gone. Two PRs now in, both rerendered, one with noarch (#6) one without (#7). We can see how they fare..

**Pull request closed without merging**
