### PR TITLE
simple build bump test

### PR DESCRIPTION
**Pull request by gidden**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gidden** [comment]
Hi @conda-forge/staged-recipes team. This is the feedstock originating from conda-forge/staged-recipes#5904 and conda-forge/staged-recipes#5918. It appears that all new PRs to this recipe are failing. This is an example of such a failure with just the build number being updated. Can you provide any suggestions of how to address this or forums which I should bring the bug/error?

Cc @jakirkham @isuruf @mariusvniekerk

**Comment by djsutherland** [comment]
@conda-forge-admin, please rerender.

The process may have been confused by the earlier build that broke halfway through....

**Comment by djsutherland** [comment]
Oops, shouldn't have done this in the PR.

**Comment by gidden** [comment]
For now, I have addressed this issue by removing `noarch`, let me know if you'd like me to reopen.

**Pull request closed without merging**
